"""empty message

Revision ID: 83f36c1ea613
Revises: 92d8727bbbb5
Create Date: 2016-12-14 00:07:28.726517

"""

# revision identifiers, used by Alembic.
revision = '83f36c1ea613'
down_revision = '92d8727bbbb5'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['username'])

    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    ### end Alembic commands ###
