"""empty message

Revision ID: 8645016bd6da
Revises: None
Create Date: 2016-11-13 15:20:39.128673

"""

# revision identifiers, used by Alembic.
revision = '8645016bd6da'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('username', sa.String(length=50), nullable=True))
    op.create_unique_constraint(None, 'user', ['username'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_column('user', 'username')
    ### end Alembic commands ###
